[service.backend]
root = "backend"

[service.backend.build]
command = "cd backend && go build -o app main.go"

[service.backend.deploy]
command = "cd backend && ./app"

[service.backend.env]
GIN_MODE = "release"
MONGODB_URL = "${{ MONGODB_URL }}"
JWT_SECRET = "${{ JWT_SECRET }}"
DB_NAME = "${{ DB_NAME }}"
COLLECTION_NAME = "${{ COLLECTION_NAME }}"

[service.frontend]
root = "frontend"

[service.frontend.build]
command = "npm install && npm run build"

[service.frontend.deploy]
command = "npm run preview"

[service.frontend.env]
VITE_API_BASE_URL = "${{ VITE_API_BASE_URL }}"